### ISSUE TITLE
AttributeError: 'EgoCar' object has no attribute 'get_auto_control'

### ISSUE THREAD

**Issue by jameskobee** [zhackzey/IntersectNav#2]
When I try to run evaluate.py, there doesn't seem to be any code related to `get_auto_control`
https://github.com/zhackzey/IntersectNav/blob/f996c54e94a006c00b2b796e28513f2dffb6d849/env/ego_car.py#L167

**Comment by zhackzey** [comment]
Hello, jameskobee. Thanks for pointing out the problem. This name error has been fixed.
